### ISSUE TITLE
Random JPEG corruption

### ISSUE THREAD

**Issue by kvintettbombur** [daniellerch/hstego#2]
The code works fine, but in some cases, it randomly appears to generate invalid JPEGs. For example, using the call

```
hstego.py embed secret.txt source.jpg stego.jpg MyP4ssw0rd101
```

results in a jpeg with a visible artifact, where the extraction with `hstego.py extract` throws an error:

```
Error: Corrupt JPEG data: 46 extraneous bytes before marker 0xd9
Traceback (most recent call last):
  File "/usr/local/bin/hstego.py", line 104, in <module>
    juniw.extract(stego_img_path, password, output_msg_path)
  File "/usr/local/lib/python3.8/dist-packages/hstegolib.py", line 533, in extract
    plain = cipher.decrypt(bytes(ciphertext))
  File "/usr/local/lib/python3.8/dist-packages/hstegolib.py", line 180, in decrypt
    self.aes_decrypt()
  File "/usr/local/lib/python3.8/dist-packages/hstegolib.py", line 175, in aes_decrypt
    self.decrypted = unpad(decrypted, AES.block_size)
  File "/home/c11/.local/lib/python3.8/site-packages/Crypto/Util/Padding.py", line 92, in unpad
    raise ValueError("Padding is incorrect.")
ValueError: Padding is incorrect.
```

This seems to happen especially when choosing a larger secret size, such as 1000 characters in this case, and happens completely randomly in about 10% of the cases.

Source:
![source](https://user-images.githubusercontent.com/107404556/173360411-2ea66eb0-4892-4757-9bc4-58953a42ee55.jpg)

Stego:
![stego1](https://user-images.githubusercontent.com/107404556/173360485-61fea2ec-6c22-4b53-a356-46af76e8a0ab.jpg)

Another broken stego:
![stego2](https://user-images.githubusercontent.com/107404556/173361110-d856e5b2-9185-4d17-9f40-4be11884cdcb.jpg)

In contrast, a correct stego:
![stego3](https://user-images.githubusercontent.com/107404556/173361195-e5e43684-490d-4c3b-b824-c1ee5e24fd58.jpg)

Secret
```
11wLUd2r2CfBRjEiUUHwXUim3pAwJXVIWPe10eq3pWCEDQxivEcQgJCj8KdQr8iMVMLWzBZofj2t7zZ0C9QqScabvB1kKh6p2PJ1ZspEZr5hpeh1o6rEgPpbboMtWQgYq0XPqMbQBh5yJmz5qpKXC98lwUcSvJyjHV87phVyOYxiJul9h5guDpd7JGZCXVvoy1tljNj7vgnEZZMGc2Anrmu92RLZwHLsICdzZL7TzsfYP1p04xntji2l9OI4dbutoWtLrymqoSPEREETBzNvhNeplvrMWjEIF7e63OvrqK5GWHjfH6YwUDjD6aYcImtXrVcutXjirpyL4f0LkZIEkzPqavQsfJNWozOgW8OLvKezzfJjCZvwYJk6EAwuSKOEHluotG7oYmlYP4FbdBVCSDGeNDWnXv0ogsaX9gJfQ4Dp7ROkaru24BgPMDDt6Dfk5EHCuasKc39jUVS4MK4QVjppw0i2DMmHa1TUbLmBNvvrOLukfw89fxybyhb91LQbMu3vDp5ai0Q6LIoyCw7st6Rpl1zmKNLfHOaTBf1tdPxwflvsh0iY69Mp8JZTgu8wGgPRKOKvmHsR0lHhlzEq7afFtFgZ9oVOTspnF8i1PYSOJk53jHtorW4klkItXlH0e4ntCTsa2KyJ23MkLDYAkatVJBMqwdoYiZPu2HS2aQMcSgMlutveTo7mxUas7MQnvogw58yfZIG1zckrVfVxSchP6IFCcgzYSdSVmO9JhPKez4VThyQ9a7XfNmr0QoWqSyMEMVX1upfrr8KW6iefqBKBvB9KxfAPdUbyz6zrtdjkj1HqkvVY4nhxwrFtWOJ8ss4qz3hseObOQqC8jfelSLiMCwFhKWpCPr2MuiCX4ltUb5aIiE38YkUkgjP0ECAb3Bxwr7TvtMOSPyl5BoDjYhRCOrCa1LB5W81NESG7meX9bIEm5RTb6uoSj03jJEopLnAZDRez3B8eUKQXjr8pkwFTvIAEXy2qjAPwZ1td
```

**Comment by daniellerch** [comment]
Fixed! Install using:

sudo pip3 install git+https://github.com/daniellerch/hstego.git@v0.2

Thank you very much for reporting.
